export enum FrameCodes {
    UNKOWN = 0,
    READ_COIL = 1,
    READ_DISCRETE_INPUT = 2,
    READ_HOLDING_REGISTERS = 3,
    READ_INPUT_REGISTERS = 4,
    WRITE_SINGLE_COIL = 5,
    WRITE_SINGLE_HOLDING_REGISTER = 6,
    WRITE_MULTIPLE_COILS = 15,
    WRITE_MULTIPLE_HOLDING_REGISTERS = 16
}

export const FrameDictionary = {
    0: "UNKOWN",
    1: "READ_COIL",
    2: "READ_DISCRETE_INPUT",
    3: "READ_HOLDING_REGISTERS",
    4: "READ_INPUT_REGISTERS",
    5: "WRITE_SINGLE_COIL",
    6: "WRITE_SINGLE_HOLDING_REGISTER",
    15: "WRITE_MULTIPLE_COILS",
    16: "WRITE_MULTIPLE_HOLDING_REGISTERS"
}
